version: '3.1'

services:

  postgres:
    container_name: postgres
    image: mdillon/postgis:11-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_PASSWORD: mozio
      POSTGRES_USER: mozio  
      POSTGRES_DB: mozio

  redis:
    container_name: redis
    image: redis:5-alpine
    restart: always
    ports:
      - 127.0.0.1:6379:6379

  django:
    container_name: django
    build:
      context: ../backend
      dockerfile: ../ops/Dockerfile
    volumes:
      - ./../backend/src:/code
    restart: always
    ports: 
      - 0.0.0.0:80:8080
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_HOST=postgres


volumes:
  postgres-data:
    driver: local